name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build-windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r GUI/requirements.txt -U
          pip install -r CLI/requirements.txt -U
          pip install pyinstaller

      - name: Build GUI
        run: pyinstaller -y -F -w -i "GUI/DUCE-LOGO.ico" --name "DUCE-GUI-windows" --add-data="GUI/pack;pack/" --add-data "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\cloudscraper;./cloudscraper/" "GUI/duce.py"

      - name: Build CLI
        run: pyinstaller -y -F -c -i "CLI/DUCE-LOGO.ico" --name "DUCE-CLI-windows" --add-data="CLI/colors.py;." --add-data "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\cloudscraper;./cloudscraper/" "CLI/duce.py"

      - name: Upload GUI.exe
        uses: actions/upload-artifact@v1
        with:
          name: DUCE-GUI-windows.exe
          path: ./dist/DUCE-GUI-windows.exe
      - name: Upload CLI.exe
        uses: actions/upload-artifact@v1
        with:
          name: DUCE-CLI-windows.exe
          path: ./dist/DUCE-CLI-windows.exe
