name: 'Delete old releases'
on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1 
          delete_tags:true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}