name: Build

on:
  workflow_dispatch:

jobs:

  build-windows:
    name: TEST
    #needs: createrelease
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper
          c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\cloudscraper
      - name: Build with pyinstaller for windows
        run: pyinstaller -y -F -w -i "DUCE-LOGO.ico" --name "Discounted-Udemy-Course-Enroller-windows" --add-data="pack;pack/" --add-data "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\cloudscraper;./cloudscraper/" "udemy.py"
